### PR TITLE
Wip

### PR DESCRIPTION
**Pull request by Jos-Ven**

### CODE REVIEW

**Comment by andrewtholt** [comment]
Just tried building ESP32 from your WIP branch and now have the following error:

/home/andrewh/Source/Forth/esp-idf-v3.1.4/components/bootloader_support/src/bootloader_common.c: In function 'bootloader_common_erase_part_type_data':
/home/andrewh/Source/Forth/esp-idf-v3.1.4/components/bootloader_support/src/bootloader_common.c:125:65: error: argument to 'sizeof' in 'strncpy' call is the same expression as the source; did you mean to use the size of the destination? [-Werror=sizeof-pointer-memaccess]
                 strncpy(label, (char *)&partition->label, sizeof(partition->label));
                                                                 ^
cc1: some warnings being treated as errors
make[3]: *** [/home/andrewh/Source/Forth/esp-idf-v3.1.4/make/component_wrapper.mk:286: src/bootloader_common.o] Error 1
make[2]: *** [/home/andrewh/Source/Forth/esp-idf-v3.1.4/make/project.mk:493: component-bootloader_support-build] Error 2
make[1]: *** [/home/andrewh/Source/Forth/esp-idf-v3.1.4/components/bootloader/Makefile.projbuild:41: /home/andrewh/Source/Forth/cforth-jos/build/esp32/sdk_build/build/bootloader/bootloader.bin] Error 2
make: *** [Makefile:33: forth.elf] Error 2


Looks like you are using the length of the source, rather than the destination.

HTH

Andrew

**Comment by MitchBradley** [comment]
> Looks like you are using the length of the source, rather than the destination.

Considering that the code is question is in the IDF, the antecedent of "you" would have to be "some Espressif engineer", not "Mitch Bradley".

Personally, I don't see anything wrong with the code.  label's size is one more than that of partition->label, label is zero-filled at initialization, and the comment says that partition->label is not necessarily null-terminated.

Regardless, you could try making the size argument sizeof(label)-1 , and then taking up the issue with the ESP-IDF folks on that repository.

**Comment by MitchBradley** [comment]
https://gcc.gnu.org/gcc-4.8/porting_to.html

regardless of how to fix it, the problem is an interaction between GCC and the ESP code.

**Comment by Jos-Ven** [comment]
Hi,
Thanks for trying my version of LWIP.
Perhaps it helps if I show to you how I build cforth.

$su
$cd /home/pi/cf/cforth/build/esp32
$rm -rf forth  makebi  makeccalls makename  meta  version build *.*
$COMPORT=/dev/ttyUSB0 make flash

My esp-idf-v3.1.4 is at: /home/pi/cf

I see you created: /home/andrewh/Source/Forth/cforth-jos
Does cforth work when you copy the cforth tree of the MitchBradley 
version into that location.


Op 25-9-2021 om 16:34 schreef Andrew Holt:

**Comment by andrewtholt** [comment]
I updated tools etc, and it now works (yay)

**Comment by Jos-Ven** [comment]
Hi Mitch, These updates enables you to use:
Low power features like Deep-sleep, lightsleep and wake up. 
ESP-NOW for reliable fast wireless  communications between 2 Esp32 systems without a router or accespoints. 
With or without confirmations within a limited time specification. 
Interrupts and queues with some limitations.

**Comment by MitchBradley** [comment]
Looks good, I merged it.

**Pull request merged**
