### PR TITLE
Wip Solves the problems with tccalls.fth and removed short-timeout in xmodem.fth

### PR DESCRIPTION
**Pull request by Jos-Ven**
Perhaps this will make it easier to promote the wip branch to the main branch

### CODE REVIEW

**Comment by quozl** [comment]
Are you sure about these changes?  Open each commit in a new tab to review what you changed.  I did that, and was slightly puzzled.

**Comment by Jos-Ven** [comment]
Sorry for the confusing. Here is what has been done:
Yesterday the problem was pushed in my wip branch.
Then Mitch solved it (Thanks again).
And today I pushed the solutions to the wip branch to solve the 
problems that were previously pushed to my wip branch.
For that several "git add" lines and then 1 commit and 1 push was used.
There was also a merge needed to solve a problem with GIT. (Seem to happen after git status)
That was also corrected today. So it should be alright now,
All in all 4 commits. 
Thanks in advance.

**Comment by quozl** [comment]
Thanks.  It was the change from 128 to 140 in doccall that surprised me.

**Comment by Jos-Ven** [comment]
That was needed in order to use more then 127 ccalls in extend.c

**Pull request merged**
